# Generated by Django 3.1.6 on 2021-02-13 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_p', models.CharField(max_length=256)),
                ('org_name', models.CharField(max_length=256)),
                ('per_name', models.CharField(max_length=256)),
                ('org_email', models.EmailField(max_length=256, unique=True)),
                ('org_phone', models.IntegerField()),
                ('add1', models.CharField(max_length=1000)),
                ('add2', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('pincode', models.CharField(max_length=256)),
                ('lat', models.CharField(max_length=256)),
                ('lon', models.CharField(max_length=256)),
                ('value', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
