# Generated by Django 3.1.6 on 2021-02-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_vendoraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoraccount',
            name='id_p',
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='lat',
            field=models.CharField(default='12231', max_length=256),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='lon',
            field=models.CharField(default='12123', max_length=256),
        ),
    ]
