# Generated by Django 3.1.6 on 2021-02-14 06:32

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210214_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoraccount',
            name='created_by',
            field=models.ForeignKey(default=account.models.Account, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
